version: '3'

services:
  nestjs-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nestserver:latest
    container_name: nestjs_server
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo_db
    restart: always

  mongo_db:
    image: 'bitnami/mongodb:latest'
    container_name: mongo_db
    ports:
      - '27017:27017' 
    environment:
      - MONGODB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - 'mongodb_master_data:/bitnami'
    env_file:
      - .env
volumes:
  mongodb_master_data:
    driver: local
